# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comments.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63omments.proto\"\"\n\rCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\"2\n\x0b\x43ommentProp\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\x12\x12\n\ncomment_id\x18\x02 \x01(\x05\"0\n\x0f\x43ommentResponse\x12\x1d\n\x07results\x18\x01 \x03(\x0b\x32\x0c.CommentProp2<\n\x08\x63omments\x12\x30\n\x0cget_comments\x12\x0e.CourseRequest\x1a\x10.CommentResponseb\x06proto3'
)




_COURSEREQUEST = _descriptor.Descriptor(
  name='CourseRequest',
  full_name='CourseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='course_id', full_name='CourseRequest.course_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=52,
)


_COMMENTPROP = _descriptor.Descriptor(
  name='CommentProp',
  full_name='CommentProp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='comment', full_name='CommentProp.comment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment_id', full_name='CommentProp.comment_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=104,
)


_COMMENTRESPONSE = _descriptor.Descriptor(
  name='CommentResponse',
  full_name='CommentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='CommentResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=154,
)

_COMMENTRESPONSE.fields_by_name['results'].message_type = _COMMENTPROP
DESCRIPTOR.message_types_by_name['CourseRequest'] = _COURSEREQUEST
DESCRIPTOR.message_types_by_name['CommentProp'] = _COMMENTPROP
DESCRIPTOR.message_types_by_name['CommentResponse'] = _COMMENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CourseRequest = _reflection.GeneratedProtocolMessageType('CourseRequest', (_message.Message,), {
  'DESCRIPTOR' : _COURSEREQUEST,
  '__module__' : 'comments_pb2'
  # @@protoc_insertion_point(class_scope:CourseRequest)
  })
_sym_db.RegisterMessage(CourseRequest)

CommentProp = _reflection.GeneratedProtocolMessageType('CommentProp', (_message.Message,), {
  'DESCRIPTOR' : _COMMENTPROP,
  '__module__' : 'comments_pb2'
  # @@protoc_insertion_point(class_scope:CommentProp)
  })
_sym_db.RegisterMessage(CommentProp)

CommentResponse = _reflection.GeneratedProtocolMessageType('CommentResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMENTRESPONSE,
  '__module__' : 'comments_pb2'
  # @@protoc_insertion_point(class_scope:CommentResponse)
  })
_sym_db.RegisterMessage(CommentResponse)



_COMMENTS = _descriptor.ServiceDescriptor(
  name='comments',
  full_name='comments',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=156,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_comments',
    full_name='comments.get_comments',
    index=0,
    containing_service=None,
    input_type=_COURSEREQUEST,
    output_type=_COMMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMENTS)

DESCRIPTOR.services_by_name['comments'] = _COMMENTS

# @@protoc_insertion_point(module_scope)
