# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comments_pb2 as comments__pb2


class commentsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_comments = channel.unary_unary(
                '/comments/get_comments',
                request_serializer=comments__pb2.CourseRequest.SerializeToString,
                response_deserializer=comments__pb2.CommentResponse.FromString,
                )


class commentsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_comments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_commentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_comments': grpc.unary_unary_rpc_method_handler(
                    servicer.get_comments,
                    request_deserializer=comments__pb2.CourseRequest.FromString,
                    response_serializer=comments__pb2.CommentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comments', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class comments(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_comments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comments/get_comments',
            comments__pb2.CourseRequest.SerializeToString,
            comments__pb2.CommentResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
